# Generated by Django 4.1.3 on 2022-11-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="catalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название товара"),
                ),
                ("description", models.CharField(max_length=254)),
                ("sex", models.CharField(max_length=100, verbose_name="Пол")),
                ("size", models.CharField(max_length=6, verbose_name="Размер")),
                ("price", models.FloatField()),
                ("image", models.ImageField(blank=True, upload_to="images")),
            ],
        ),
    ]
