# Generated by Django 4.1.3 on 2022-11-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_orderitem_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catalog",
            name="description",
        ),
        migrations.AddField(
            model_name="catalog",
            name="category",
            field=models.CharField(
                choices=[
                    ("S", "Shirt"),
                    ("P", "Pants"),
                    ("J", "Jacket"),
                    ("s", "Shoes"),
                ],
                default="S",
                max_length=1,
                verbose_name="Категория",
            ),
            preserve_default=False,
        ),
    ]
