# Generated by Django 4.1.3 on 2022-11-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_catalog_description_catalog_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalog",
            name="category",
            field=models.CharField(
                choices=[("S", "Shirt"), ("P", "Pants"), ("J", "Jacket")],
                max_length=1,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="sex",
            field=models.CharField(
                choices=[("M", "Для мужчин"), ("W", "Для женщин")],
                max_length=1,
                verbose_name="Пол",
            ),
        ),
        migrations.AlterField(
            model_name="catalog",
            name="size",
            field=models.CharField(
                choices=[
                    ("XS", "XS"),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                ],
                max_length=3,
                verbose_name="Размер",
            ),
        ),
    ]
