# Generated by Django 4.1.3 on 2022-11-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_catalog_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalog",
            name="slug",
            field=models.SlugField(default="test_product"),
            preserve_default=False,
        ),
    ]
