# Generated by Django 4.1.3 on 2022-11-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_catalog_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catalog",
            name="slug",
        ),
    ]
