# Generated by Django 4.1.3 on 2022-11-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_remove_catalog_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalog",
            name="quantity",
            field=models.IntegerField(default=1, verbose_name="Количество"),
        ),
    ]
